Feature/template upgrade
Open-Dataplatform/template-ingress-adapter pull request #1
Opened 2021-11-19 09:34 UTC by jensrix

With these changes:
- the adapter can be run either in an input time interval or based on the state file. 
- if the reguested time interval is too large (or the adapter is too far behind), the time interval is split and multiple retrivals/uploads are made. 
- more Cookiecutter inputs have been added to make it easier to start a new project. 

We need to handle the two TODO_TEMPLATEs before we merge.

2021-11-22 06:52 UTC, runethorbek commented
Lad mig starte med at sige, at det er super at lave det bedre - for det trænger det til.

Så et par overordnede ting:
- Jeg tror stadig det er best practice at have __name__ == ... nederst (som det der), så def main lige over, og så videre op. Dvs. man definerer de funktioner, som der bruges før man bruger dem. (ved godt det ikke er overholdt i alle repos).

Derudover tænker jeg, at vi kunne strukturere programmet med en __main__.py fil (ved godt det ikke var tilfældet før, men det blev lavet meget hurtigt).

Det man så kunne have i __main__ er læsning af configuration (det er hvad vi har prøvet at overholde andre steder). Det afkobler den del fra det andet kode.

2021-11-24 10:51 UTC, jensrix commented
Hej @runethorbek. Så vidt jeg kan læse mig til, så er det en smagssag, om `main()` skal være øverst eller nederst, men det er fint at gøre det ensartet. 

Jeg har lavet en `__main__.py`. Burde vi egentlig flytte noget af koden til `__init__.py`? Det kunne for eksempel være initiering af `logger` eller hentning af argumenter.

Jeg synes `__main__.main()` er lidt for lang/kompleks. Måske skal noget af koden deri brydes op i mindre dele?

2021-11-24 12:40 UTC, runethorbek commented
Hej @jensrix,
Vedr: main: Jeg ved ikke om det er et krav. Tror bare det er normen. Og det stammer fra gamle dage, hvor det var nødvendigt at man definerede ting før man brugte dem. Derfør tror jeg de fleste gør det.

Vedr __main__: Det gør at man kan gøre det som et modul: python -m ingress_dims (og ikke python ingress_dims.__main__.main()

Ja vi kunne saktens bruge __init__. Det har vi dog ikke gjort andre steder.

2021-11-24 15:09 UTC, jensrix commented
@runethorbek og jeg har snakket om at dele koden i main() op i mindre dele. Men hvis vi trækker løkken fra linie 95 til 108 i __main__.py ud i en separat funktion, så får vi bare mange input parametre:
```Python
def retrieve_and_upload_data(adapter, ingress_api, from_date, to_date, max_interval_to_retrieve, run_adapter_based_on_state_file)```
Jeg kan ikke lige se hvordan løkken ellers skal splittes.

2022-01-03 10:56 UTC, TheBurningDude requested changes

2022-01-03 10:56 UTC, TheBurningDude commented on ingress-{{cookiecutter.repo_name}}/conf.example.ini
> +max_interval_to_retrieve = P7DT
Er der eksempler på hvordan man skriver disse formater, hvis man fx gerne vil hente 1 dag eller 1 time?

2022-01-03 10:56 UTC, TheBurningDude commented on ingress-{{cookiecutter.repo_name}}/conf.ini
> +source = {{cookiecutter.name}}
Denne skal vidst rettes til:
```suggestion
source = {{cookiecutter.dataset_guid}}
```

2022-01-03 10:56 UTC, TheBurningDude commented on ingress-{{cookiecutter.repo_name}}/run.bat
>  CALL E:\ingress-{{cookiecutter.repo_name}}\venv\Scripts\deactivate.bat
Hele run.bat filen skal fjernes fra template, da det kun blev brugt i de gamle DataHub BI løsninger.

2022-01-03 11:45 UTC, jensrix commented on ingress-{{cookiecutter.repo_name}}/conf.example.ini
> +max_interval_to_retrieve = P7DT
Ja, det står beskrevet i README filen.

2022-01-03 11:51 UTC, jensrix commented on ingress-{{cookiecutter.repo_name}}/run.bat
>  CALL E:\ingress-{{cookiecutter.repo_name}}\venv\Scripts\deactivate.bat
Du har ret. Jeg har slettet den.

2022-01-03 12:02 UTC, TheBurningDude approved these changes

2022-01-03 12:05 UTC, merged